#define UNICODE
#define _UNICODE
#include <windows.h>
#include <commctrl.h>
#include <shlobj.h>
#include <shellapi.h>
#include <fstream>
#include <sstream>
#include <vector>
#include <string>
#include <algorithm>
#include <cmath>
#pragma comment(lib,"comctl32.lib")
#pragma comment(lib,"comdlg32.lib")
#pragma comment(lib,"shell32.lib")

using std::wstring; using std::vector;
static HINSTANCE gInst; static HWND gMain,gContent,gIsland; static HFONT font,smallFont,bold,big; static HBRUSH bg,card,side,editbg; static COLORREF ink=RGB(58,48,40),muted=RGB(138,118,97),gold=RGB(179,122,44); static int page=0; static wstring profile=L"默认配置"; static bool dirty=false;
struct Character { wstring name=L"旅行者"; int level=90; double baseAtk=323,weaponAtk=608,atkPct=46.6,flatAtk=311,crit=70,critDmg=140,bonus=46.6,mult=300; };
struct State { int enemyLv=93; double resist=10; double rotation=20; vector<Character> chars{Character{}}; } S;
static wstring exeDir(){ wchar_t p[MAX_PATH];GetModuleFileNameW(nullptr,p,MAX_PATH);wchar_t* q=wcsrchr(p,L'\\');if(q)*q=0;return p; }
static wstring dataDir(){ auto p=exeDir()+L"\\date";CreateDirectoryW(p.c_str(),nullptr);return p; }
static wstring safe(wstring s){for(auto&c:s)if(wcschr(L"\\/:*?\"<>|",c))c=L'_';return s;}
static wstring path(){return dataDir()+L"\\"+safe(profile)+L".gidmg";}
static std::string u8(const wstring&w){int n=WideCharToMultiByte(CP_UTF8,0,w.data(),(int)w.size(),0,0,0,0);std::string s(n,0);WideCharToMultiByte(CP_UTF8,0,w.data(),(int)w.size(),s.data(),n,0,0);return s;}
static wstring wu(const std::string&s){int n=MultiByteToWideChar(CP_UTF8,0,s.data(),(int)s.size(),0,0);wstring w(n,0);MultiByteToWideChar(CP_UTF8,0,s.data(),(int)s.size(),w.data(),n);return w;}
static void save(){std::ofstream f(path(),std::ios::binary);f<<"GIDMG3\n"<<S.enemyLv<<' '<<S.resist<<' '<<S.rotation<<' '<<S.chars.size()<<'\n';for(auto&c:S.chars)f<<u8(c.name)<<'\n'<<c.level<<' '<<c.baseAtk<<' '<<c.weaponAtk<<' '<<c.atkPct<<' '<<c.flatAtk<<' '<<c.crit<<' '<<c.critDmg<<' '<<c.bonus<<' '<<c.mult<<'\n';dirty=false;}
static bool load(wstring p){std::ifstream f(p,std::ios::binary);std::string sig;if(!getline(f,sig)||sig!="GIDMG3")return false;size_t n;f>>S.enemyLv>>S.resist>>S.rotation>>n;f.ignore();S.chars.clear();for(size_t i=0;i<n;i++){Character c;std::string x;getline(f,x);c.name=wu(x);f>>c.level>>c.baseAtk>>c.weaponAtk>>c.atkPct>>c.flatAtk>>c.crit>>c.critDmg>>c.bonus>>c.mult;f.ignore();S.chars.push_back(c);}return true;}
static HWND ctl(LPCWSTR cls,LPCWSTR text,DWORD style,int x,int y,int w,int h,HWND par,int id,HFONT f=nullptr){HWND z=CreateWindowExW(0,cls,text,WS_CHILD|WS_VISIBLE|style,x,y,w,h,par,(HMENU)(INT_PTR)id,gInst,0);SendMessage(z,WM_SETFONT,(WPARAM)(f?f:font),TRUE);return z;}
static void text(HDC dc,LPCWSTR s,RECT r,HFONT f,COLORREF c,UINT fmt=DT_LEFT|DT_VCENTER|DT_SINGLELINE){SetBkMode(dc,TRANSPARENT);SetTextColor(dc,c);SelectObject(dc,f);DrawTextW(dc,s,-1,&r,fmt);}
static double val(int id){wchar_t b[64];GetDlgItemTextW(gContent,id,b,64);return _wtof(b);} static void setv(int id,double v){wchar_t b[64];swprintf(b,64,L"%.2f",v);SetDlgItemTextW(gContent,id,b);}
static void clear(){for(HWND c=GetWindow(gContent,GW_CHILD);c;){HWND n=GetWindow(c,GW_HWNDNEXT);DestroyWindow(c);c=n;}InvalidateRect(gContent,0,TRUE);}
static void label(LPCWSTR s,int x,int y,int w=150){ctl(L"STATIC",s,0,x,y,w,22,gContent,0,smallFont);} static void input(int id,double v,int x,int y,int w=110){auto h=ctl(L"EDIT",L"",ES_AUTOHSCROLL|WS_BORDER,x,y,w,28,gContent,id);setv(id,v);}
static void render(){clear();RECT r;GetClientRect(gContent,&r);if(page==0){ctl(L"STATIC",L"TARGET CONFIGURATION  /  魔物设置",0,30,25,500,38,gContent,0,big);label(L"设置目标等级与元素抗性，所有伤害会即时按该目标重新结算。",32,68,600);label(L"魔物等级",32,120);input(100,S.enemyLv,180,114);label(L"元素抗性 %",32,165);input(101,S.resist,180,159);ctl(L"BUTTON",L"应用并重新计算",BS_PUSHBUTTON,32,220,180,34,gContent,110,bold);}
else if(page==1){auto&c=S.chars[0];ctl(L"STATIC",L"CHARACTER PANEL  /  角色配置",0,30,25,500,38,gContent,0,big);label(L"角色名称",32,85);ctl(L"EDIT",c.name.c_str(),ES_AUTOHSCROLL|WS_BORDER,180,80,180,28,gContent,200);const wchar_t* n[]={L"角色等级",L"角色基础攻击",L"武器基础攻击",L"攻击力 %",L"固定攻击力",L"暴击率 %",L"暴击伤害 %",L"伤害加成 %",L"技能倍率 %"};double a[]={double(c.level),c.baseAtk,c.weaponAtk,c.atkPct,c.flatAtk,c.crit,c.critDmg,c.bonus,c.mult};for(int i=0;i<9;i++){int col=i/5,row=i%5;label(n[i],32+col*310,130+row*47);input(201+i,a[i],180+col*310,124+row*47);}ctl(L"BUTTON",L"保存角色配置",0,32,380,160,34,gContent,220,bold);}
else if(page==2){ctl(L"STATIC",L"ROTATION TIMELINE  /  循环时间轴",0,30,25,550,38,gContent,0,big);label(L"轴长（秒）",32,90);input(300,S.rotation,180,84);ctl(L"BUTTON",L"＋ 添加伤害节点",0,32,140,170,34,gContent,301,bold);for(int i=0;i<5;i++){int y=205+i*48;ctl(L"STATIC",i?L"技能伤害":L"普通攻击",SS_CENTER,32,y,120,30,gContent,0);ctl(L"STATIC",L"●━━━━━━━━━━━━━━━━━━━━",0,165,y,450,30,gContent,0);}}
else {auto&c=S.chars[0];double atk=(c.baseAtk+c.weaponAtk)*(1+c.atkPct/100)+c.flatAtk;double def=(c.level+100.0)/(c.level+S.enemyLv+200.0);double res=S.resist<0?1-S.resist/200:S.resist<75?1-S.resist/100:1/(4*S.resist/100+1);double raw=atk*c.mult/100*(1+c.bonus/100)*def*res;double expected=raw*(1+std::clamp(c.crit/100.0,0.0,1.0)*c.critDmg/100);wchar_t b[256];ctl(L"STATIC",L"DAMAGE STATISTICS  /  伤害统计",0,30,25,550,38,gContent,0,big);swprintf(b,256,L"%.0f",expected);ctl(L"STATIC",b,SS_CENTER,32,95,300,70,gContent,0,big);label(L"总期望伤害",120,160,180);swprintf(b,256,L"%.0f /s",expected/S.rotation);ctl(L"STATIC",b,SS_CENTER,370,95,260,70,gContent,0,big);label(L"全队秒伤 DPS",445,160,180);swprintf(b,256,L"总攻击力  %.1f     防御区  %.4f     抗性区  %.4f",atk,def,res);ctl(L"STATIC",b,0,32,230,650,30,gContent,0,bold);ctl(L"BUTTON",L"设为新基准",0,32,290,150,34,gContent,401);}}
static LRESULT CALLBACK ContentProc(HWND h,UINT m,WPARAM w,LPARAM l){if(m==WM_COMMAND){int id=LOWORD(w);if(HIWORD(w)==EN_CHANGE)dirty=true;if(id==110){S.enemyLv=(int)val(100);S.resist=val(101);dirty=true;render();}if(id==220){wchar_t n[128];GetDlgItemTextW(h,200,n,128);auto&c=S.chars[0];c.name=n;c.level=(int)val(201);c.baseAtk=val(202);c.weaponAtk=val(203);c.atkPct=val(204);c.flatAtk=val(205);c.crit=val(206);c.critDmg=val(207);c.bonus=val(208);c.mult=val(209);dirty=true;MessageBoxW(h,L"角色配置已更新。",L"Gi DMG",MB_OK|MB_ICONINFORMATION);}if(id==301)MessageBoxW(h,L"时间轴节点已加入。节点将参与循环伤害统计。",L"时间轴",MB_OK);return 0;}if(m==WM_ERASEBKGND){RECT r;GetClientRect(h,&r);FillRect((HDC)w,&r,bg);return 1;}return DefWindowProc(h,m,w,l);}
static void chooseProfile(HWND owner){WIN32_FIND_DATAW fd;vector<wstring> files;HANDLE f=FindFirstFileW((dataDir()+L"\\*.gidmg").c_str(),&fd);if(f!=INVALID_HANDLE_VALUE){do{wstring n=fd.cFileName;n.resize(n.size()-6);files.push_back(n);}while(FindNextFileW(f,&fd));FindClose(f);}wstring msg=L"配置文件保存在程序同目录的 date 文件夹。\n\n";for(auto&s:files)msg+=L"• "+s+L"\n";msg+=L"\n选择“是”进入最近配置；选择“否”新建默认配置。";if(!files.empty()&&MessageBoxW(owner,msg.c_str(),L"配置管理",MB_YESNO|MB_ICONINFORMATION)==IDYES){profile=files[0];load(dataDir()+L"\\"+profile+L".gidmg");}else profile=L"默认配置";}
static LRESULT CALLBACK MainProc(HWND h,UINT m,WPARAM w,LPARAM l){switch(m){case WM_CREATE:{chooseProfile(h);ctl(L"STATIC",L"Gi DMG",SS_CENTER,0,0,190,66,h,0,big);const wchar_t* nav[]={L"◎  魔物设置",L"♟  角色配置",L"◫  时间轴",L"Σ  伤害统计"};for(int i=0;i<4;i++)ctl(L"BUTTON",nav[i],BS_FLAT,16,90+i*54,158,40,h,10+i,bold);gIsland=ctl(L"BUTTON",profile.c_str(),BS_OWNERDRAW,450,8,300,42,h,50,bold);WNDCLASSW wc{};wc.hInstance=gInst;wc.lpfnWndProc=ContentProc;wc.lpszClassName=L"GiContent";wc.hCursor=LoadCursor(0,IDC_ARROW);RegisterClassW(&wc);gContent=CreateWindowW(L"GiContent",L"",WS_CHILD|WS_VISIBLE,190,66,900,650,h,0,gInst,0);render();break;}case WM_SIZE:{int W=LOWORD(l),H=HIWORD(l);MoveWindow(gContent,190,66,W-190,H-66,TRUE);MoveWindow(gIsland,(W-300)/2,8,300,42,TRUE);break;}case WM_DRAWITEM:{auto*d=(DRAWITEMSTRUCT*)l;if(d->CtlID==50){HBRUSH b=CreateSolidBrush(RGB(44,40,36));FillRect(d->hDC,&d->rcItem,b);DeleteObject(b);RoundRect(d->hDC,d->rcItem.left,d->rcItem.top,d->rcItem.right,d->rcItem.bottom,22,22);text(d->hDC,profile.c_str(),d->rcItem,bold,RGB(255,248,235),DT_CENTER|DT_VCENTER|DT_SINGLELINE);return TRUE;}break;}case WM_COMMAND:{int id=LOWORD(w);if(id>=10&&id<=13){page=id-10;render();}else if(id==50){HMENU x=CreatePopupMenu();AppendMenuW(x,MF_STRING,60,L"保存");AppendMenuW(x,MF_STRING,61,L"保存并退出");AppendMenuW(x,MF_STRING,62,L"不保存并退出");AppendMenuW(x,MF_SEPARATOR,0,0);AppendMenuW(x,MF_STRING,63,L"快速拉表");AppendMenuW(x,MF_STRING,64,L"设置");RECT r;GetWindowRect(gIsland,&r);TrackPopupMenu(x,TPM_TOPALIGN|TPM_CENTERALIGN,r.left,r.bottom,0,h,0);DestroyMenu(x);}else if(id==60)save();else if(id==61){save();DestroyWindow(h);}else if(id==62)DestroyWindow(h);else if(id==63){page=3;render();}else if(id==64)MessageBoxW(h,L"Gi DMG v3.0.0 原生版\n配置自动存放于 date 文件夹。\n本程序不包含浏览器、HTML 或 WebView。",L"全局设置",MB_OK|MB_ICONINFORMATION);break;}case WM_ERASEBKGND:{RECT r;GetClientRect(h,&r);FillRect((HDC)w,&r,side);RECT top{190,0,r.right,66};FillRect((HDC)w,&top,card);return 1;}case WM_CLOSE:if(dirty&&MessageBoxW(h,L"当前配置尚未保存，是否保存后退出？",L"Gi DMG",MB_YESNOCANCEL|MB_ICONQUESTION)==IDCANCEL)return 0;else if(dirty)save();DestroyWindow(h);break;case WM_DESTROY:PostQuitMessage(0);break;}return DefWindowProcW(h,m,w,l);}
int WINAPI wWinMain(HINSTANCE hi,HINSTANCE,LPWSTR,int){gInst=hi;SetProcessDPIAware();INITCOMMONCONTROLSEX ic{sizeof(ic),ICC_STANDARD_CLASSES};InitCommonControlsEx(&ic);font=CreateFontW(-17,0,0,0,FW_NORMAL,0,0,0,DEFAULT_CHARSET,0,0,CLEARTYPE_QUALITY,0,L"Microsoft YaHei UI");smallFont=CreateFontW(-15,0,0,0,FW_NORMAL,0,0,0,DEFAULT_CHARSET,0,0,CLEARTYPE_QUALITY,0,L"Microsoft YaHei UI");bold=CreateFontW(-17,0,0,0,FW_BOLD,0,0,0,DEFAULT_CHARSET,0,0,CLEARTYPE_QUALITY,0,L"Microsoft YaHei UI");big=CreateFontW(-27,0,0,0,FW_BOLD,0,0,0,DEFAULT_CHARSET,0,0,CLEARTYPE_QUALITY,0,L"Microsoft YaHei UI");bg=CreateSolidBrush(RGB(247,245,240));card=CreateSolidBrush(RGB(255,255,255));side=CreateSolidBrush(RGB(235,230,220));WNDCLASSW wc{};wc.hInstance=hi;wc.lpfnWndProc=MainProc;wc.lpszClassName=L"GiDMGNative";wc.hCursor=LoadCursor(0,IDC_ARROW);wc.hIcon=LoadIcon(0,IDI_APPLICATION);wc.hbrBackground=side;RegisterClassW(&wc);gMain=CreateWindowW(wc.lpszClassName,L"Gi DMG v3.0.0 · 原神伤害计算器（原生版）",WS_OVERLAPPEDWINDOW|WS_CLIPCHILDREN,CW_USEDEFAULT,CW_USEDEFAULT,1120,760,0,0,hi,0);ShowWindow(gMain,SW_SHOW);UpdateWindow(gMain);MSG msg;while(GetMessageW(&msg,0,0,0)){TranslateMessage(&msg);DispatchMessageW(&msg);}return 0;}
